name: Build & Deploy
on:
  push:
    branches: main

  pull_request:
    branches: main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false

      # - name: Install Bun
      #   run: curl -fsSL bun.sh/install | bash

      # - name: Source Bun
      #   run: source /home/runner/.bashrc

      - name: Install
        uses: oven-sh/setup-bun@v1
      - run: bun install

      - name: Lint
        uses: oven-sh/setup-bun@v1
      - run: bun lint

      - name: Build
        uses: oven-sh/setup-bun@v1
      - run: bun run build
        # env:
          # NODE_ENV: production
        
      - name: Deploy
        if: ${{ github.event_name != 'pull_request' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist